### ISSUE TITLE
force:source:deploy not respecting double quotes in args

### ISSUE THREAD

**Issue by Clint-Chester** [forcedotcom/salesforcedx-actions#1]
### Issue
I am trying to use the [force:source:deploy](https://developer.salesforce.com/docs/atlas.en-us.sfdx_cli_reference.meta/sfdx_cli_reference/cli_reference_force_source.htm#cli_reference_deploy) by providing a comma separated list of file paths in which some of the file names have spaces. However when passing the double quotes in the args, I'm getting sfdx errors with unrecognized file paths due to the file name being chopped off.

### Steps to reproduce
The step below assumes that authentication, default user names and GitHub outputs have been setup correctly. The following is an example of the deploy step.
```
- name: Deploy files
  uses: forcedotcom/salesforcedx-actions@master
    with:
      args: 'force:source:deploy -p "${{ steps.files.outputs.files-to-deploy }}" -u ${{ secrets.SALESFORCE_USERNAME }}'
```
This is the files-to-deploy variable
```
force-app/main/default/layouts/Contact-Contact Layout.layout-meta.xml, force-app/main/default/objects/Contact/Contact.object-meta.xml
```

### Expected Outcome
Files deploy correctly to target environment. Confirmed this by doing a direct npm install with the sfdx-cli and not using the docker action.

### Actual Outcome
Following is the output received.
```
ERROR running force:source:deploy:  Unexpected arguments: Layout.layout-meta.xml,, force-app/main/default/objects/Contact/Contact.object-meta.xml
```

If I'm passing in the arguments incorrectly that would be an ideal news story 😄 any help is greatly appreciated. Thanks!
